// Code generated by protoc-gen-go. DO NOT EDIT.
// source: t1.proto

package t1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Terra struct {
	// Types that are valid to be assigned to Mona:
	//	*Terra_T
	//	*Terra_Qwint
	Mona                 isTerra_Mona `protobuf_oneof:"mona"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Terra) Reset()         { *m = Terra{} }
func (m *Terra) String() string { return proto.CompactTextString(m) }
func (*Terra) ProtoMessage()    {}
func (*Terra) Descriptor() ([]byte, []int) {
	return fileDescriptor_t1_2a16fb00f8abe618, []int{0}
}
func (m *Terra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Terra.Unmarshal(m, b)
}
func (m *Terra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Terra.Marshal(b, m, deterministic)
}
func (dst *Terra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Terra.Merge(dst, src)
}
func (m *Terra) XXX_Size() int {
	return xxx_messageInfo_Terra.Size(m)
}
func (m *Terra) XXX_DiscardUnknown() {
	xxx_messageInfo_Terra.DiscardUnknown(m)
}

var xxx_messageInfo_Terra proto.InternalMessageInfo

type isTerra_Mona interface {
	isTerra_Mona()
}

type Terra_T struct {
	T int32 `protobuf:"varint,1,opt,name=t,proto3,oneof"`
}

type Terra_Qwint struct {
	Qwint int32 `protobuf:"varint,2,opt,name=qwint,proto3,oneof"`
}

func (*Terra_T) isTerra_Mona() {}

func (*Terra_Qwint) isTerra_Mona() {}

func (m *Terra) GetMona() isTerra_Mona {
	if m != nil {
		return m.Mona
	}
	return nil
}

func (m *Terra) GetT() int32 {
	if x, ok := m.GetMona().(*Terra_T); ok {
		return x.T
	}
	return 0
}

func (m *Terra) GetQwint() int32 {
	if x, ok := m.GetMona().(*Terra_Qwint); ok {
		return x.Qwint
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Terra) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Terra_OneofMarshaler, _Terra_OneofUnmarshaler, _Terra_OneofSizer, []interface{}{
		(*Terra_T)(nil),
		(*Terra_Qwint)(nil),
	}
}

func _Terra_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Terra)
	// mona
	switch x := m.Mona.(type) {
	case *Terra_T:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.T))
	case *Terra_Qwint:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Qwint))
	case nil:
	default:
		return fmt.Errorf("Terra.Mona has unexpected type %T", x)
	}
	return nil
}

func _Terra_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Terra)
	switch tag {
	case 1: // mona.t
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Mona = &Terra_T{int32(x)}
		return true, err
	case 2: // mona.qwint
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Mona = &Terra_Qwint{int32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Terra_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Terra)
	// mona
	switch x := m.Mona.(type) {
	case *Terra_T:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.T))
	case *Terra_Qwint:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Qwint))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Terra)(nil), "terra")
}

func init() { proto.RegisterFile("t1.proto", fileDescriptor_t1_2a16fb00f8abe618) }

var fileDescriptor_t1_2a16fb00f8abe618 = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0x31, 0xd4, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe7, 0x62, 0x2d, 0x49, 0x2d, 0x2a, 0x4a, 0x14, 0xe2, 0xe3,
	0x62, 0x2c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0xf5, 0x60, 0x08, 0x62, 0x2c, 0x11, 0x12, 0xe3,
	0x62, 0x2d, 0x2c, 0xcf, 0xcc, 0x2b, 0x91, 0x60, 0x82, 0x8a, 0x41, 0xb8, 0x4e, 0x6c, 0x5c, 0x2c,
	0xb9, 0xf9, 0x79, 0x89, 0x49, 0x6c, 0x60, 0xfd, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7,
	0xc1, 0x9b, 0x34, 0x4b, 0x00, 0x00, 0x00,
}
